/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.osp.icecap.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DataEntry service. Represents a row in the &quot;ICECAP_DataEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.osp.icecap.model.impl.DataEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.osp.icecap.model.impl.DataEntryImpl</code>.
 * </p>
 *
 * @author Jerry H. Seo
 * @see DataEntry
 * @generated
 */
@ProviderType
public interface DataEntryModel
	extends BaseModel<DataEntry>, GroupedModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a data entry model instance should use the {@link DataEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this data entry.
	 *
	 * @return the primary key of this data entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this data entry.
	 *
	 * @param primaryKey the primary key of this data entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this data entry.
	 *
	 * @return the uuid of this data entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this data entry.
	 *
	 * @param uuid the uuid of this data entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the data entry ID of this data entry.
	 *
	 * @return the data entry ID of this data entry
	 */
	public long getDataEntryId();

	/**
	 * Sets the data entry ID of this data entry.
	 *
	 * @param dataEntryId the data entry ID of this data entry
	 */
	public void setDataEntryId(long dataEntryId);

	/**
	 * Returns the company ID of this data entry.
	 *
	 * @return the company ID of this data entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this data entry.
	 *
	 * @param companyId the company ID of this data entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this data entry.
	 *
	 * @return the group ID of this data entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this data entry.
	 *
	 * @param groupId the group ID of this data entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this data entry.
	 *
	 * @return the user ID of this data entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this data entry.
	 *
	 * @param userId the user ID of this data entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this data entry.
	 *
	 * @return the user uuid of this data entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this data entry.
	 *
	 * @param userUuid the user uuid of this data entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this data entry.
	 *
	 * @return the user name of this data entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this data entry.
	 *
	 * @param userName the user name of this data entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this data entry.
	 *
	 * @return the create date of this data entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this data entry.
	 *
	 * @param createDate the create date of this data entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this data entry.
	 *
	 * @return the modified date of this data entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this data entry.
	 *
	 * @param modifiedDate the modified date of this data entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this data entry.
	 *
	 * @return the status of this data entry
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this data entry.
	 *
	 * @param status the status of this data entry
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this data entry.
	 *
	 * @return the status by user ID of this data entry
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this data entry.
	 *
	 * @param statusByUserId the status by user ID of this data entry
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this data entry.
	 *
	 * @return the status by user uuid of this data entry
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this data entry.
	 *
	 * @param statusByUserUuid the status by user uuid of this data entry
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this data entry.
	 *
	 * @return the status by user name of this data entry
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this data entry.
	 *
	 * @param statusByUserName the status by user name of this data entry
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this data entry.
	 *
	 * @return the status date of this data entry
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this data entry.
	 *
	 * @param statusDate the status date of this data entry
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the data pack ID of this data entry.
	 *
	 * @return the data pack ID of this data entry
	 */
	public long getDataPackId();

	/**
	 * Sets the data pack ID of this data entry.
	 *
	 * @param dataPackId the data pack ID of this data entry
	 */
	public void setDataPackId(long dataPackId);

	/**
	 * Returns the data section ID of this data entry.
	 *
	 * @return the data section ID of this data entry
	 */
	public long getDataSectionId();

	/**
	 * Sets the data section ID of this data entry.
	 *
	 * @param dataSectionId the data section ID of this data entry
	 */
	public void setDataSectionId(long dataSectionId);

	/**
	 * Returns the data set ID of this data entry.
	 *
	 * @return the data set ID of this data entry
	 */
	public long getDataSetId();

	/**
	 * Sets the data set ID of this data entry.
	 *
	 * @param dataSetId the data set ID of this data entry
	 */
	public void setDataSetId(long dataSetId);

	/**
	 * Returns the data collection ID of this data entry.
	 *
	 * @return the data collection ID of this data entry
	 */
	public long getDataCollectionId();

	/**
	 * Sets the data collection ID of this data entry.
	 *
	 * @param dataCollectionId the data collection ID of this data entry
	 */
	public void setDataCollectionId(long dataCollectionId);

	/**
	 * Returns the access url of this data entry.
	 *
	 * @return the access url of this data entry
	 */
	@AutoEscape
	public String getAccessURL();

	/**
	 * Sets the access url of this data entry.
	 *
	 * @param accessURL the access url of this data entry
	 */
	public void setAccessURL(String accessURL);

	/**
	 * Returns the path type of this data entry.
	 *
	 * @return the path type of this data entry
	 */
	@AutoEscape
	public String getPathType();

	/**
	 * Sets the path type of this data entry.
	 *
	 * @param pathType the path type of this data entry
	 */
	public void setPathType(String pathType);

	/**
	 * Returns the copied from of this data entry.
	 *
	 * @return the copied from of this data entry
	 */
	public long getCopiedFrom();

	/**
	 * Sets the copied from of this data entry.
	 *
	 * @param copiedFrom the copied from of this data entry
	 */
	public void setCopiedFrom(long copiedFrom);

	/**
	 * Returns <code>true</code> if this data entry is approved.
	 *
	 * @return <code>true</code> if this data entry is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this data entry is denied.
	 *
	 * @return <code>true</code> if this data entry is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this data entry is a draft.
	 *
	 * @return <code>true</code> if this data entry is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this data entry is expired.
	 *
	 * @return <code>true</code> if this data entry is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this data entry is inactive.
	 *
	 * @return <code>true</code> if this data entry is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this data entry is incomplete.
	 *
	 * @return <code>true</code> if this data entry is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this data entry is pending.
	 *
	 * @return <code>true</code> if this data entry is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this data entry is scheduled.
	 *
	 * @return <code>true</code> if this data entry is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}