/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.osp.icecap.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DataTypeLink service. Represents a row in the &quot;ICECAP_DataTypeLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.osp.icecap.model.impl.DataTypeLinkModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.osp.icecap.model.impl.DataTypeLinkImpl</code>.
 * </p>
 *
 * @author Jerry H. Seo
 * @see DataTypeLink
 * @generated
 */
@ProviderType
public interface DataTypeLinkModel extends BaseModel<DataTypeLink> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a data type link model instance should use the {@link DataTypeLink} interface instead.
	 */

	/**
	 * Returns the primary key of this data type link.
	 *
	 * @return the primary key of this data type link
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this data type link.
	 *
	 * @param primaryKey the primary key of this data type link
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the data uuid of this data type link.
	 *
	 * @return the data uuid of this data type link
	 */
	@AutoEscape
	public String getDataUuid();

	/**
	 * Sets the data uuid of this data type link.
	 *
	 * @param dataUuid the data uuid of this data type link
	 */
	public void setDataUuid(String dataUuid);

	/**
	 * Returns the data type ID of this data type link.
	 *
	 * @return the data type ID of this data type link
	 */
	public long getDataTypeId();

	/**
	 * Sets the data type ID of this data type link.
	 *
	 * @param dataTypeId the data type ID of this data type link
	 */
	public void setDataTypeId(long dataTypeId);

}