/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.osp.icecap.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DataEntry service. Represents a row in the &quot;ICECAP_DataEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.osp.icecap.model.impl.DataEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.osp.icecap.model.impl.DataEntryImpl</code>.
 * </p>
 *
 * @author Jerry H. Seo
 * @see DataEntry
 * @generated
 */
@ProviderType
public interface DataEntryModel extends BaseModel<DataEntry>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a data entry model instance should use the {@link DataEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this data entry.
	 *
	 * @return the primary key of this data entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this data entry.
	 *
	 * @param primaryKey the primary key of this data entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data entry ID of this data entry.
	 *
	 * @return the data entry ID of this data entry
	 */
	public long getDataEntryId();

	/**
	 * Sets the data entry ID of this data entry.
	 *
	 * @param dataEntryId the data entry ID of this data entry
	 */
	public void setDataEntryId(long dataEntryId);

	/**
	 * Returns the data collection name of this data entry.
	 *
	 * @return the data collection name of this data entry
	 */
	@AutoEscape
	public String getDataCollectionName();

	/**
	 * Sets the data collection name of this data entry.
	 *
	 * @param dataCollectionName the data collection name of this data entry
	 */
	public void setDataCollectionName(String dataCollectionName);

	/**
	 * Returns the company ID of this data entry.
	 *
	 * @return the company ID of this data entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this data entry.
	 *
	 * @param companyId the company ID of this data entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this data entry.
	 *
	 * @return the group ID of this data entry
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this data entry.
	 *
	 * @param groupId the group ID of this data entry
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this data entry.
	 *
	 * @return the user ID of this data entry
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this data entry.
	 *
	 * @param userId the user ID of this data entry
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this data entry.
	 *
	 * @return the user uuid of this data entry
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this data entry.
	 *
	 * @param userUuid the user uuid of this data entry
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the create date of this data entry.
	 *
	 * @return the create date of this data entry
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this data entry.
	 *
	 * @param createDate the create date of this data entry
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the path of this data entry.
	 *
	 * @return the path of this data entry
	 */
	@AutoEscape
	public String getPath();

	/**
	 * Sets the path of this data entry.
	 *
	 * @param path the path of this data entry
	 */
	public void setPath(String path);

	/**
	 * Returns the sequence no of this data entry.
	 *
	 * @return the sequence no of this data entry
	 */
	public int getSequenceNo();

	/**
	 * Sets the sequence no of this data entry.
	 *
	 * @param sequenceNo the sequence no of this data entry
	 */
	public void setSequenceNo(int sequenceNo);

	/**
	 * Returns the record count of this data entry.
	 *
	 * @return the record count of this data entry
	 */
	public int getRecordCount();

	/**
	 * Sets the record count of this data entry.
	 *
	 * @param recordCount the record count of this data entry
	 */
	public void setRecordCount(int recordCount);

	/**
	 * Returns the sequence delimeter of this data entry.
	 *
	 * @return the sequence delimeter of this data entry
	 */
	@AutoEscape
	public String getSequenceDelimeter();

	/**
	 * Sets the sequence delimeter of this data entry.
	 *
	 * @param sequenceDelimeter the sequence delimeter of this data entry
	 */
	public void setSequenceDelimeter(String sequenceDelimeter);

}