/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.osp.icecap.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DataSection service. Represents a row in the &quot;ICECAP_DataSection&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.osp.icecap.model.impl.DataSectionModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.osp.icecap.model.impl.DataSectionImpl</code>.
 * </p>
 *
 * @author Jerry H. Seo
 * @see DataSection
 * @generated
 */
@ProviderType
public interface DataSectionModel
	extends BaseModel<DataSection>, GroupedModel, ShardedModel,
			StagedAuditedModel, WorkflowedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a data section model instance should use the {@link DataSection} interface instead.
	 */

	/**
	 * Returns the primary key of this data section.
	 *
	 * @return the primary key of this data section
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this data section.
	 *
	 * @param primaryKey the primary key of this data section
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this data section.
	 *
	 * @return the uuid of this data section
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this data section.
	 *
	 * @param uuid the uuid of this data section
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the data section ID of this data section.
	 *
	 * @return the data section ID of this data section
	 */
	public long getDataSectionId();

	/**
	 * Sets the data section ID of this data section.
	 *
	 * @param dataSectionId the data section ID of this data section
	 */
	public void setDataSectionId(long dataSectionId);

	/**
	 * Returns the company ID of this data section.
	 *
	 * @return the company ID of this data section
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this data section.
	 *
	 * @param companyId the company ID of this data section
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the group ID of this data section.
	 *
	 * @return the group ID of this data section
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this data section.
	 *
	 * @param groupId the group ID of this data section
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the user ID of this data section.
	 *
	 * @return the user ID of this data section
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this data section.
	 *
	 * @param userId the user ID of this data section
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this data section.
	 *
	 * @return the user uuid of this data section
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this data section.
	 *
	 * @param userUuid the user uuid of this data section
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this data section.
	 *
	 * @return the user name of this data section
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this data section.
	 *
	 * @param userName the user name of this data section
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this data section.
	 *
	 * @return the create date of this data section
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this data section.
	 *
	 * @param createDate the create date of this data section
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this data section.
	 *
	 * @return the modified date of this data section
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this data section.
	 *
	 * @param modifiedDate the modified date of this data section
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this data section.
	 *
	 * @return the status of this data section
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this data section.
	 *
	 * @param status the status of this data section
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this data section.
	 *
	 * @return the status by user ID of this data section
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this data section.
	 *
	 * @param statusByUserId the status by user ID of this data section
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this data section.
	 *
	 * @return the status by user uuid of this data section
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this data section.
	 *
	 * @param statusByUserUuid the status by user uuid of this data section
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this data section.
	 *
	 * @return the status by user name of this data section
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this data section.
	 *
	 * @param statusByUserName the status by user name of this data section
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this data section.
	 *
	 * @return the status date of this data section
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this data section.
	 *
	 * @param statusDate the status date of this data section
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the data collection ID of this data section.
	 *
	 * @return the data collection ID of this data section
	 */
	public long getDataCollectionId();

	/**
	 * Sets the data collection ID of this data section.
	 *
	 * @param dataCollectionId the data collection ID of this data section
	 */
	public void setDataCollectionId(long dataCollectionId);

	/**
	 * Returns the data set ID of this data section.
	 *
	 * @return the data set ID of this data section
	 */
	public long getDataSetId();

	/**
	 * Sets the data set ID of this data section.
	 *
	 * @param dataSetId the data set ID of this data section
	 */
	public void setDataSetId(long dataSetId);

	/**
	 * Returns the data type ID of this data section.
	 *
	 * @return the data type ID of this data section
	 */
	public long getDataTypeId();

	/**
	 * Sets the data type ID of this data section.
	 *
	 * @param dataTypeId the data type ID of this data section
	 */
	public void setDataTypeId(long dataTypeId);

	/**
	 * Returns the name of this data section.
	 *
	 * @return the name of this data section
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this data section.
	 *
	 * @param name the name of this data section
	 */
	public void setName(String name);

	/**
	 * Returns the version of this data section.
	 *
	 * @return the version of this data section
	 */
	@AutoEscape
	public String getVersion();

	/**
	 * Sets the version of this data section.
	 *
	 * @param version the version of this data section
	 */
	public void setVersion(String version);

	/**
	 * Returns the copied from of this data section.
	 *
	 * @return the copied from of this data section
	 */
	public long getCopiedFrom();

	/**
	 * Sets the copied from of this data section.
	 *
	 * @param copiedFrom the copied from of this data section
	 */
	public void setCopiedFrom(long copiedFrom);

	/**
	 * Returns the has meta data of this data section.
	 *
	 * @return the has meta data of this data section
	 */
	public boolean getHasMetaData();

	/**
	 * Returns <code>true</code> if this data section is has meta data.
	 *
	 * @return <code>true</code> if this data section is has meta data; <code>false</code> otherwise
	 */
	public boolean isHasMetaData();

	/**
	 * Sets whether this data section is has meta data.
	 *
	 * @param hasMetaData the has meta data of this data section
	 */
	public void setHasMetaData(boolean hasMetaData);

	/**
	 * Returns <code>true</code> if this data section is approved.
	 *
	 * @return <code>true</code> if this data section is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this data section is denied.
	 *
	 * @return <code>true</code> if this data section is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this data section is a draft.
	 *
	 * @return <code>true</code> if this data section is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this data section is expired.
	 *
	 * @return <code>true</code> if this data section is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this data section is inactive.
	 *
	 * @return <code>true</code> if this data section is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this data section is incomplete.
	 *
	 * @return <code>true</code> if this data section is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this data section is pending.
	 *
	 * @return <code>true</code> if this data section is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this data section is scheduled.
	 *
	 * @return <code>true</code> if this data section is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

}