/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.osp.icecap.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DataCollectionLayout service. Represents a row in the &quot;ICECAP_DataCollectionLayout&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.osp.icecap.model.impl.DataCollectionLayoutModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.osp.icecap.model.impl.DataCollectionLayoutImpl</code>.
 * </p>
 *
 * @author Jerry H. Seo
 * @see DataCollectionLayout
 * @generated
 */
@ProviderType
public interface DataCollectionLayoutModel
	extends BaseModel<DataCollectionLayout> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a data collection layout model instance should use the {@link DataCollectionLayout} interface instead.
	 */

	/**
	 * Returns the primary key of this data collection layout.
	 *
	 * @return the primary key of this data collection layout
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this data collection layout.
	 *
	 * @param primaryKey the primary key of this data collection layout
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the data collection ID of this data collection layout.
	 *
	 * @return the data collection ID of this data collection layout
	 */
	public long getDataCollectionId();

	/**
	 * Sets the data collection ID of this data collection layout.
	 *
	 * @param dataCollectionId the data collection ID of this data collection layout
	 */
	public void setDataCollectionId(long dataCollectionId);

	/**
	 * Returns the layout of this data collection layout.
	 *
	 * @return the layout of this data collection layout
	 */
	@AutoEscape
	public String getLayout();

	/**
	 * Sets the layout of this data collection layout.
	 *
	 * @param layout the layout of this data collection layout
	 */
	public void setLayout(String layout);

}