/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.osp.icecap.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the DataAnalysisLayout service. Represents a row in the &quot;ICECAP_DataAnalysisLayout&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.osp.icecap.model.impl.DataAnalysisLayoutModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.osp.icecap.model.impl.DataAnalysisLayoutImpl</code>.
 * </p>
 *
 * @author Jerry H. Seo
 * @see DataAnalysisLayout
 * @generated
 */
@ProviderType
public interface DataAnalysisLayoutModel extends BaseModel<DataAnalysisLayout> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a data analysis layout model instance should use the {@link DataAnalysisLayout} interface instead.
	 */

	/**
	 * Returns the primary key of this data analysis layout.
	 *
	 * @return the primary key of this data analysis layout
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this data analysis layout.
	 *
	 * @param primaryKey the primary key of this data analysis layout
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the data uuid of this data analysis layout.
	 *
	 * @return the data uuid of this data analysis layout
	 */
	@AutoEscape
	public String getDataUuid();

	/**
	 * Sets the data uuid of this data analysis layout.
	 *
	 * @param dataUuid the data uuid of this data analysis layout
	 */
	public void setDataUuid(String dataUuid);

	/**
	 * Returns the layout of this data analysis layout.
	 *
	 * @return the layout of this data analysis layout
	 */
	@AutoEscape
	public String getLayout();

	/**
	 * Sets the layout of this data analysis layout.
	 *
	 * @param layout the layout of this data analysis layout
	 */
	public void setLayout(String layout);

}