/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.osp.icecap.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.osp.icecap.model.DataAnalysisLayout;
import com.osp.icecap.model.DataAnalysisLayoutModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the DataAnalysisLayout service. Represents a row in the &quot;ICECAP_DataAnalysisLayout&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>DataAnalysisLayoutModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DataAnalysisLayoutImpl}.
 * </p>
 *
 * @author Jerry H. Seo
 * @see DataAnalysisLayoutImpl
 * @generated
 */
@ProviderType
public class DataAnalysisLayoutModelImpl
	extends BaseModelImpl<DataAnalysisLayout>
	implements DataAnalysisLayoutModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a data analysis layout model instance should use the <code>DataAnalysisLayout</code> interface instead.
	 */
	public static final String TABLE_NAME = "ICECAP_DataAnalysisLayout";

	public static final Object[][] TABLE_COLUMNS = {
		{"dataUuid", Types.VARCHAR}, {"layout", Types.VARCHAR},
		{"applyLevel", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("dataUuid", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("layout", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("applyLevel", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ICECAP_DataAnalysisLayout (dataUuid VARCHAR(75) not null primary key,layout VARCHAR(75) null,applyLevel VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP =
		"drop table ICECAP_DataAnalysisLayout";

	public static final String ORDER_BY_JPQL =
		" ORDER BY dataAnalysisLayout.dataUuid ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ICECAP_DataAnalysisLayout.dataUuid ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long APPLYLEVEL_COLUMN_BITMASK = 1L;

	public static final long DATAUUID_COLUMN_BITMASK = 2L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public DataAnalysisLayoutModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _dataUuid;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setDataUuid(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dataUuid;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return DataAnalysisLayout.class;
	}

	@Override
	public String getModelClassName() {
		return DataAnalysisLayout.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DataAnalysisLayout, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DataAnalysisLayout, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DataAnalysisLayout, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DataAnalysisLayout)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DataAnalysisLayout, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DataAnalysisLayout, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DataAnalysisLayout)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DataAnalysisLayout, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DataAnalysisLayout, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, DataAnalysisLayout>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			DataAnalysisLayout.class.getClassLoader(), DataAnalysisLayout.class,
			ModelWrapper.class);

		try {
			Constructor<DataAnalysisLayout> constructor =
				(Constructor<DataAnalysisLayout>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<DataAnalysisLayout, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DataAnalysisLayout, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<DataAnalysisLayout, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<DataAnalysisLayout, Object>>();
		Map<String, BiConsumer<DataAnalysisLayout, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<DataAnalysisLayout, ?>>();

		attributeGetterFunctions.put(
			"dataUuid", DataAnalysisLayout::getDataUuid);
		attributeSetterBiConsumers.put(
			"dataUuid",
			(BiConsumer<DataAnalysisLayout, String>)
				DataAnalysisLayout::setDataUuid);
		attributeGetterFunctions.put("layout", DataAnalysisLayout::getLayout);
		attributeSetterBiConsumers.put(
			"layout",
			(BiConsumer<DataAnalysisLayout, String>)
				DataAnalysisLayout::setLayout);
		attributeGetterFunctions.put(
			"applyLevel", DataAnalysisLayout::getApplyLevel);
		attributeSetterBiConsumers.put(
			"applyLevel",
			(BiConsumer<DataAnalysisLayout, String>)
				DataAnalysisLayout::setApplyLevel);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getDataUuid() {
		if (_dataUuid == null) {
			return "";
		}
		else {
			return _dataUuid;
		}
	}

	@Override
	public void setDataUuid(String dataUuid) {
		_columnBitmask |= DATAUUID_COLUMN_BITMASK;

		if (_originalDataUuid == null) {
			_originalDataUuid = _dataUuid;
		}

		_dataUuid = dataUuid;
	}

	public String getOriginalDataUuid() {
		return GetterUtil.getString(_originalDataUuid);
	}

	@Override
	public String getLayout() {
		if (_layout == null) {
			return "";
		}
		else {
			return _layout;
		}
	}

	@Override
	public void setLayout(String layout) {
		_layout = layout;
	}

	@Override
	public String getApplyLevel() {
		if (_applyLevel == null) {
			return "";
		}
		else {
			return _applyLevel;
		}
	}

	@Override
	public void setApplyLevel(String applyLevel) {
		_columnBitmask |= APPLYLEVEL_COLUMN_BITMASK;

		if (_originalApplyLevel == null) {
			_originalApplyLevel = _applyLevel;
		}

		_applyLevel = applyLevel;
	}

	public String getOriginalApplyLevel() {
		return GetterUtil.getString(_originalApplyLevel);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public DataAnalysisLayout toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DataAnalysisLayout>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DataAnalysisLayoutImpl dataAnalysisLayoutImpl =
			new DataAnalysisLayoutImpl();

		dataAnalysisLayoutImpl.setDataUuid(getDataUuid());
		dataAnalysisLayoutImpl.setLayout(getLayout());
		dataAnalysisLayoutImpl.setApplyLevel(getApplyLevel());

		dataAnalysisLayoutImpl.resetOriginalValues();

		return dataAnalysisLayoutImpl;
	}

	@Override
	public int compareTo(DataAnalysisLayout dataAnalysisLayout) {
		String primaryKey = dataAnalysisLayout.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DataAnalysisLayout)) {
			return false;
		}

		DataAnalysisLayout dataAnalysisLayout = (DataAnalysisLayout)obj;

		String primaryKey = dataAnalysisLayout.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		DataAnalysisLayoutModelImpl dataAnalysisLayoutModelImpl = this;

		dataAnalysisLayoutModelImpl._originalDataUuid =
			dataAnalysisLayoutModelImpl._dataUuid;

		dataAnalysisLayoutModelImpl._originalApplyLevel =
			dataAnalysisLayoutModelImpl._applyLevel;

		dataAnalysisLayoutModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DataAnalysisLayout> toCacheModel() {
		DataAnalysisLayoutCacheModel dataAnalysisLayoutCacheModel =
			new DataAnalysisLayoutCacheModel();

		dataAnalysisLayoutCacheModel.dataUuid = getDataUuid();

		String dataUuid = dataAnalysisLayoutCacheModel.dataUuid;

		if ((dataUuid != null) && (dataUuid.length() == 0)) {
			dataAnalysisLayoutCacheModel.dataUuid = null;
		}

		dataAnalysisLayoutCacheModel.layout = getLayout();

		String layout = dataAnalysisLayoutCacheModel.layout;

		if ((layout != null) && (layout.length() == 0)) {
			dataAnalysisLayoutCacheModel.layout = null;
		}

		dataAnalysisLayoutCacheModel.applyLevel = getApplyLevel();

		String applyLevel = dataAnalysisLayoutCacheModel.applyLevel;

		if ((applyLevel != null) && (applyLevel.length() == 0)) {
			dataAnalysisLayoutCacheModel.applyLevel = null;
		}

		return dataAnalysisLayoutCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DataAnalysisLayout, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DataAnalysisLayout, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DataAnalysisLayout, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((DataAnalysisLayout)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<DataAnalysisLayout, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<DataAnalysisLayout, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DataAnalysisLayout, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((DataAnalysisLayout)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DataAnalysisLayout>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _dataUuid;
	private String _originalDataUuid;
	private String _layout;
	private String _applyLevel;
	private String _originalApplyLevel;
	private long _columnBitmask;
	private DataAnalysisLayout _escapedModel;

}