/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.osp.icecap.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.osp.icecap.model.DataTypeLink;
import com.osp.icecap.model.DataTypeLinkModel;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the DataTypeLink service. Represents a row in the &quot;ICECAP_DataTypeLink&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>DataTypeLinkModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DataTypeLinkImpl}.
 * </p>
 *
 * @author Jerry H. Seo
 * @see DataTypeLinkImpl
 * @generated
 */
@ProviderType
public class DataTypeLinkModelImpl
	extends BaseModelImpl<DataTypeLink> implements DataTypeLinkModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a data type link model instance should use the <code>DataTypeLink</code> interface instead.
	 */
	public static final String TABLE_NAME = "ICECAP_DataTypeLink";

	public static final Object[][] TABLE_COLUMNS = {
		{"dataUuid", Types.VARCHAR}, {"dataTypeId", Types.BIGINT}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("dataUuid", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dataTypeId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ICECAP_DataTypeLink (dataUuid VARCHAR(75) not null primary key,dataTypeId LONG)";

	public static final String TABLE_SQL_DROP =
		"drop table ICECAP_DataTypeLink";

	public static final String ORDER_BY_JPQL =
		" ORDER BY dataTypeLink.dataUuid ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ICECAP_DataTypeLink.dataUuid ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	public DataTypeLinkModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _dataUuid;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setDataUuid(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dataUuid;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return DataTypeLink.class;
	}

	@Override
	public String getModelClassName() {
		return DataTypeLink.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DataTypeLink, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DataTypeLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DataTypeLink, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DataTypeLink)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DataTypeLink, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DataTypeLink, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DataTypeLink)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DataTypeLink, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DataTypeLink, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, DataTypeLink>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			DataTypeLink.class.getClassLoader(), DataTypeLink.class,
			ModelWrapper.class);

		try {
			Constructor<DataTypeLink> constructor =
				(Constructor<DataTypeLink>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<DataTypeLink, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DataTypeLink, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<DataTypeLink, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<DataTypeLink, Object>>();
		Map<String, BiConsumer<DataTypeLink, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<DataTypeLink, ?>>();

		attributeGetterFunctions.put("dataUuid", DataTypeLink::getDataUuid);
		attributeSetterBiConsumers.put(
			"dataUuid",
			(BiConsumer<DataTypeLink, String>)DataTypeLink::setDataUuid);
		attributeGetterFunctions.put("dataTypeId", DataTypeLink::getDataTypeId);
		attributeSetterBiConsumers.put(
			"dataTypeId",
			(BiConsumer<DataTypeLink, Long>)DataTypeLink::setDataTypeId);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getDataUuid() {
		if (_dataUuid == null) {
			return "";
		}
		else {
			return _dataUuid;
		}
	}

	@Override
	public void setDataUuid(String dataUuid) {
		_dataUuid = dataUuid;
	}

	@Override
	public long getDataTypeId() {
		return _dataTypeId;
	}

	@Override
	public void setDataTypeId(long dataTypeId) {
		_dataTypeId = dataTypeId;
	}

	@Override
	public DataTypeLink toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, DataTypeLink>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DataTypeLinkImpl dataTypeLinkImpl = new DataTypeLinkImpl();

		dataTypeLinkImpl.setDataUuid(getDataUuid());
		dataTypeLinkImpl.setDataTypeId(getDataTypeId());

		dataTypeLinkImpl.resetOriginalValues();

		return dataTypeLinkImpl;
	}

	@Override
	public int compareTo(DataTypeLink dataTypeLink) {
		String primaryKey = dataTypeLink.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DataTypeLink)) {
			return false;
		}

		DataTypeLink dataTypeLink = (DataTypeLink)obj;

		String primaryKey = dataTypeLink.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<DataTypeLink> toCacheModel() {
		DataTypeLinkCacheModel dataTypeLinkCacheModel =
			new DataTypeLinkCacheModel();

		dataTypeLinkCacheModel.dataUuid = getDataUuid();

		String dataUuid = dataTypeLinkCacheModel.dataUuid;

		if ((dataUuid != null) && (dataUuid.length() == 0)) {
			dataTypeLinkCacheModel.dataUuid = null;
		}

		dataTypeLinkCacheModel.dataTypeId = getDataTypeId();

		return dataTypeLinkCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DataTypeLink, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DataTypeLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DataTypeLink, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((DataTypeLink)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<DataTypeLink, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<DataTypeLink, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DataTypeLink, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((DataTypeLink)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, DataTypeLink>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _dataUuid;
	private long _dataTypeId;
	private DataTypeLink _escapedModel;

}