/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.osp.icecap.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.workflow.WorkflowConstants;

import com.osp.icecap.model.DataCollection;
import com.osp.icecap.model.DataCollectionModel;
import com.osp.icecap.model.DataCollectionSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model implementation for the DataCollection service. Represents a row in the &quot;ICECAP_DataCollection&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>DataCollectionModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link DataCollectionImpl}.
 * </p>
 *
 * @author Jerry H. Seo
 * @see DataCollectionImpl
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class DataCollectionModelImpl
	extends BaseModelImpl<DataCollection> implements DataCollectionModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a data collection model instance should use the <code>DataCollection</code> interface instead.
	 */
	public static final String TABLE_NAME = "ICECAP_DataCollection";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"dataCollectionId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"status", Types.INTEGER}, {"statusByUserId", Types.BIGINT},
		{"statusByUserName", Types.VARCHAR}, {"statusDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"version", Types.VARCHAR},
		{"copiedFrom", Types.BIGINT}, {"organizationId", Types.BIGINT},
		{"hasMetaData", Types.BOOLEAN}, {"hasLayout", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dataCollectionId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("statusByUserId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("statusByUserName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("statusDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("version", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("copiedFrom", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("organizationId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("hasMetaData", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("hasLayout", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ICECAP_DataCollection (uuid_ VARCHAR(75) null,dataCollectionId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,status INTEGER,statusByUserId LONG,statusByUserName VARCHAR(75) null,statusDate DATE null,name VARCHAR(75) null,version VARCHAR(75) null,copiedFrom LONG,organizationId LONG,hasMetaData BOOLEAN,hasLayout BOOLEAN)";

	public static final String TABLE_SQL_DROP =
		"drop table ICECAP_DataCollection";

	public static final String ORDER_BY_JPQL =
		" ORDER BY dataCollection.createDate ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ICECAP_DataCollection.createDate ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long COMPANYID_COLUMN_BITMASK = 1L;

	public static final long COPIEDFROM_COLUMN_BITMASK = 2L;

	public static final long GROUPID_COLUMN_BITMASK = 4L;

	public static final long NAME_COLUMN_BITMASK = 8L;

	public static final long ORGANIZATIONID_COLUMN_BITMASK = 16L;

	public static final long STATUS_COLUMN_BITMASK = 32L;

	public static final long USERID_COLUMN_BITMASK = 64L;

	public static final long UUID_COLUMN_BITMASK = 128L;

	public static final long VERSION_COLUMN_BITMASK = 256L;

	public static final long CREATEDATE_COLUMN_BITMASK = 512L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static DataCollection toModel(DataCollectionSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		DataCollection model = new DataCollectionImpl();

		model.setUuid(soapModel.getUuid());
		model.setDataCollectionId(soapModel.getDataCollectionId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setStatus(soapModel.getStatus());
		model.setStatusByUserId(soapModel.getStatusByUserId());
		model.setStatusByUserName(soapModel.getStatusByUserName());
		model.setStatusDate(soapModel.getStatusDate());
		model.setName(soapModel.getName());
		model.setVersion(soapModel.getVersion());
		model.setCopiedFrom(soapModel.getCopiedFrom());
		model.setOrganizationId(soapModel.getOrganizationId());
		model.setHasMetaData(soapModel.isHasMetaData());
		model.setHasLayout(soapModel.isHasLayout());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<DataCollection> toModels(
		DataCollectionSoap[] soapModels) {

		if (soapModels == null) {
			return null;
		}

		List<DataCollection> models = new ArrayList<DataCollection>(
			soapModels.length);

		for (DataCollectionSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public DataCollectionModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _dataCollectionId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setDataCollectionId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _dataCollectionId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return DataCollection.class;
	}

	@Override
	public String getModelClassName() {
		return DataCollection.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<DataCollection, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<DataCollection, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DataCollection, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((DataCollection)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<DataCollection, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<DataCollection, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(DataCollection)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<DataCollection, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<DataCollection, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, DataCollection>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			DataCollection.class.getClassLoader(), DataCollection.class,
			ModelWrapper.class);

		try {
			Constructor<DataCollection> constructor =
				(Constructor<DataCollection>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<DataCollection, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<DataCollection, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<DataCollection, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<DataCollection, Object>>();
		Map<String, BiConsumer<DataCollection, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<DataCollection, ?>>();

		attributeGetterFunctions.put("uuid", DataCollection::getUuid);
		attributeSetterBiConsumers.put(
			"uuid",
			(BiConsumer<DataCollection, String>)DataCollection::setUuid);
		attributeGetterFunctions.put(
			"dataCollectionId", DataCollection::getDataCollectionId);
		attributeSetterBiConsumers.put(
			"dataCollectionId",
			(BiConsumer<DataCollection, Long>)
				DataCollection::setDataCollectionId);
		attributeGetterFunctions.put("companyId", DataCollection::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<DataCollection, Long>)DataCollection::setCompanyId);
		attributeGetterFunctions.put("groupId", DataCollection::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId",
			(BiConsumer<DataCollection, Long>)DataCollection::setGroupId);
		attributeGetterFunctions.put("userId", DataCollection::getUserId);
		attributeSetterBiConsumers.put(
			"userId",
			(BiConsumer<DataCollection, Long>)DataCollection::setUserId);
		attributeGetterFunctions.put("userName", DataCollection::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<DataCollection, String>)DataCollection::setUserName);
		attributeGetterFunctions.put(
			"createDate", DataCollection::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<DataCollection, Date>)DataCollection::setCreateDate);
		attributeGetterFunctions.put(
			"modifiedDate", DataCollection::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate",
			(BiConsumer<DataCollection, Date>)DataCollection::setModifiedDate);
		attributeGetterFunctions.put("status", DataCollection::getStatus);
		attributeSetterBiConsumers.put(
			"status",
			(BiConsumer<DataCollection, Integer>)DataCollection::setStatus);
		attributeGetterFunctions.put(
			"statusByUserId", DataCollection::getStatusByUserId);
		attributeSetterBiConsumers.put(
			"statusByUserId",
			(BiConsumer<DataCollection, Long>)
				DataCollection::setStatusByUserId);
		attributeGetterFunctions.put(
			"statusByUserName", DataCollection::getStatusByUserName);
		attributeSetterBiConsumers.put(
			"statusByUserName",
			(BiConsumer<DataCollection, String>)
				DataCollection::setStatusByUserName);
		attributeGetterFunctions.put(
			"statusDate", DataCollection::getStatusDate);
		attributeSetterBiConsumers.put(
			"statusDate",
			(BiConsumer<DataCollection, Date>)DataCollection::setStatusDate);
		attributeGetterFunctions.put("name", DataCollection::getName);
		attributeSetterBiConsumers.put(
			"name",
			(BiConsumer<DataCollection, String>)DataCollection::setName);
		attributeGetterFunctions.put("version", DataCollection::getVersion);
		attributeSetterBiConsumers.put(
			"version",
			(BiConsumer<DataCollection, String>)DataCollection::setVersion);
		attributeGetterFunctions.put(
			"copiedFrom", DataCollection::getCopiedFrom);
		attributeSetterBiConsumers.put(
			"copiedFrom",
			(BiConsumer<DataCollection, Long>)DataCollection::setCopiedFrom);
		attributeGetterFunctions.put(
			"organizationId", DataCollection::getOrganizationId);
		attributeSetterBiConsumers.put(
			"organizationId",
			(BiConsumer<DataCollection, Long>)
				DataCollection::setOrganizationId);
		attributeGetterFunctions.put(
			"hasMetaData", DataCollection::getHasMetaData);
		attributeSetterBiConsumers.put(
			"hasMetaData",
			(BiConsumer<DataCollection, Boolean>)
				DataCollection::setHasMetaData);
		attributeGetterFunctions.put("hasLayout", DataCollection::getHasLayout);
		attributeSetterBiConsumers.put(
			"hasLayout",
			(BiConsumer<DataCollection, Boolean>)DataCollection::setHasLayout);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getDataCollectionId() {
		return _dataCollectionId;
	}

	@Override
	public void setDataCollectionId(long dataCollectionId) {
		_dataCollectionId = dataCollectionId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@JSON
	@Override
	public long getStatusByUserId() {
		return _statusByUserId;
	}

	@Override
	public void setStatusByUserId(long statusByUserId) {
		_statusByUserId = statusByUserId;
	}

	@Override
	public String getStatusByUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getStatusByUserId());

			return user.getUuid();
		}
		catch (PortalException pe) {
			return "";
		}
	}

	@Override
	public void setStatusByUserUuid(String statusByUserUuid) {
	}

	@JSON
	@Override
	public String getStatusByUserName() {
		if (_statusByUserName == null) {
			return "";
		}
		else {
			return _statusByUserName;
		}
	}

	@Override
	public void setStatusByUserName(String statusByUserName) {
		_statusByUserName = statusByUserName;
	}

	@JSON
	@Override
	public Date getStatusDate() {
		return _statusDate;
	}

	@Override
	public void setStatusDate(Date statusDate) {
		_statusDate = statusDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		_columnBitmask |= NAME_COLUMN_BITMASK;

		if (_originalName == null) {
			_originalName = _name;
		}

		_name = name;
	}

	public String getOriginalName() {
		return GetterUtil.getString(_originalName);
	}

	@JSON
	@Override
	public String getVersion() {
		if (_version == null) {
			return "";
		}
		else {
			return _version;
		}
	}

	@Override
	public void setVersion(String version) {
		_columnBitmask |= VERSION_COLUMN_BITMASK;

		if (_originalVersion == null) {
			_originalVersion = _version;
		}

		_version = version;
	}

	public String getOriginalVersion() {
		return GetterUtil.getString(_originalVersion);
	}

	@JSON
	@Override
	public long getCopiedFrom() {
		return _copiedFrom;
	}

	@Override
	public void setCopiedFrom(long copiedFrom) {
		_columnBitmask |= COPIEDFROM_COLUMN_BITMASK;

		if (!_setOriginalCopiedFrom) {
			_setOriginalCopiedFrom = true;

			_originalCopiedFrom = _copiedFrom;
		}

		_copiedFrom = copiedFrom;
	}

	public long getOriginalCopiedFrom() {
		return _originalCopiedFrom;
	}

	@JSON
	@Override
	public long getOrganizationId() {
		return _organizationId;
	}

	@Override
	public void setOrganizationId(long organizationId) {
		_columnBitmask |= ORGANIZATIONID_COLUMN_BITMASK;

		if (!_setOriginalOrganizationId) {
			_setOriginalOrganizationId = true;

			_originalOrganizationId = _organizationId;
		}

		_organizationId = organizationId;
	}

	public long getOriginalOrganizationId() {
		return _originalOrganizationId;
	}

	@JSON
	@Override
	public boolean getHasMetaData() {
		return _hasMetaData;
	}

	@JSON
	@Override
	public boolean isHasMetaData() {
		return _hasMetaData;
	}

	@Override
	public void setHasMetaData(boolean hasMetaData) {
		_hasMetaData = hasMetaData;
	}

	@JSON
	@Override
	public boolean getHasLayout() {
		return _hasLayout;
	}

	@JSON
	@Override
	public boolean isHasLayout() {
		return _hasLayout;
	}

	@Override
	public void setHasLayout(boolean hasLayout) {
		_hasLayout = hasLayout;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(DataCollection.class.getName()));
	}

	@Override
	public boolean isApproved() {
		if (getStatus() == WorkflowConstants.STATUS_APPROVED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDenied() {
		if (getStatus() == WorkflowConstants.STATUS_DENIED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isDraft() {
		if (getStatus() == WorkflowConstants.STATUS_DRAFT) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isExpired() {
		if (getStatus() == WorkflowConstants.STATUS_EXPIRED) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isInactive() {
		if (getStatus() == WorkflowConstants.STATUS_INACTIVE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isIncomplete() {
		if (getStatus() == WorkflowConstants.STATUS_INCOMPLETE) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isPending() {
		if (getStatus() == WorkflowConstants.STATUS_PENDING) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public boolean isScheduled() {
		if (getStatus() == WorkflowConstants.STATUS_SCHEDULED) {
			return true;
		}
		else {
			return false;
		}
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), DataCollection.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public DataCollection toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		DataCollectionImpl dataCollectionImpl = new DataCollectionImpl();

		dataCollectionImpl.setUuid(getUuid());
		dataCollectionImpl.setDataCollectionId(getDataCollectionId());
		dataCollectionImpl.setCompanyId(getCompanyId());
		dataCollectionImpl.setGroupId(getGroupId());
		dataCollectionImpl.setUserId(getUserId());
		dataCollectionImpl.setUserName(getUserName());
		dataCollectionImpl.setCreateDate(getCreateDate());
		dataCollectionImpl.setModifiedDate(getModifiedDate());
		dataCollectionImpl.setStatus(getStatus());
		dataCollectionImpl.setStatusByUserId(getStatusByUserId());
		dataCollectionImpl.setStatusByUserName(getStatusByUserName());
		dataCollectionImpl.setStatusDate(getStatusDate());
		dataCollectionImpl.setName(getName());
		dataCollectionImpl.setVersion(getVersion());
		dataCollectionImpl.setCopiedFrom(getCopiedFrom());
		dataCollectionImpl.setOrganizationId(getOrganizationId());
		dataCollectionImpl.setHasMetaData(isHasMetaData());
		dataCollectionImpl.setHasLayout(isHasLayout());

		dataCollectionImpl.resetOriginalValues();

		return dataCollectionImpl;
	}

	@Override
	public int compareTo(DataCollection dataCollection) {
		int value = 0;

		value = DateUtil.compareTo(
			getCreateDate(), dataCollection.getCreateDate());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof DataCollection)) {
			return false;
		}

		DataCollection dataCollection = (DataCollection)obj;

		long primaryKey = dataCollection.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		DataCollectionModelImpl dataCollectionModelImpl = this;

		dataCollectionModelImpl._originalUuid = dataCollectionModelImpl._uuid;

		dataCollectionModelImpl._originalCompanyId =
			dataCollectionModelImpl._companyId;

		dataCollectionModelImpl._setOriginalCompanyId = false;

		dataCollectionModelImpl._originalGroupId =
			dataCollectionModelImpl._groupId;

		dataCollectionModelImpl._setOriginalGroupId = false;

		dataCollectionModelImpl._originalUserId =
			dataCollectionModelImpl._userId;

		dataCollectionModelImpl._setOriginalUserId = false;

		dataCollectionModelImpl._setModifiedDate = false;

		dataCollectionModelImpl._originalStatus =
			dataCollectionModelImpl._status;

		dataCollectionModelImpl._setOriginalStatus = false;

		dataCollectionModelImpl._originalName = dataCollectionModelImpl._name;

		dataCollectionModelImpl._originalVersion =
			dataCollectionModelImpl._version;

		dataCollectionModelImpl._originalCopiedFrom =
			dataCollectionModelImpl._copiedFrom;

		dataCollectionModelImpl._setOriginalCopiedFrom = false;

		dataCollectionModelImpl._originalOrganizationId =
			dataCollectionModelImpl._organizationId;

		dataCollectionModelImpl._setOriginalOrganizationId = false;

		dataCollectionModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<DataCollection> toCacheModel() {
		DataCollectionCacheModel dataCollectionCacheModel =
			new DataCollectionCacheModel();

		dataCollectionCacheModel.uuid = getUuid();

		String uuid = dataCollectionCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			dataCollectionCacheModel.uuid = null;
		}

		dataCollectionCacheModel.dataCollectionId = getDataCollectionId();

		dataCollectionCacheModel.companyId = getCompanyId();

		dataCollectionCacheModel.groupId = getGroupId();

		dataCollectionCacheModel.userId = getUserId();

		dataCollectionCacheModel.userName = getUserName();

		String userName = dataCollectionCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			dataCollectionCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			dataCollectionCacheModel.createDate = createDate.getTime();
		}
		else {
			dataCollectionCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			dataCollectionCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			dataCollectionCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		dataCollectionCacheModel.status = getStatus();

		dataCollectionCacheModel.statusByUserId = getStatusByUserId();

		dataCollectionCacheModel.statusByUserName = getStatusByUserName();

		String statusByUserName = dataCollectionCacheModel.statusByUserName;

		if ((statusByUserName != null) && (statusByUserName.length() == 0)) {
			dataCollectionCacheModel.statusByUserName = null;
		}

		Date statusDate = getStatusDate();

		if (statusDate != null) {
			dataCollectionCacheModel.statusDate = statusDate.getTime();
		}
		else {
			dataCollectionCacheModel.statusDate = Long.MIN_VALUE;
		}

		dataCollectionCacheModel.name = getName();

		String name = dataCollectionCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			dataCollectionCacheModel.name = null;
		}

		dataCollectionCacheModel.version = getVersion();

		String version = dataCollectionCacheModel.version;

		if ((version != null) && (version.length() == 0)) {
			dataCollectionCacheModel.version = null;
		}

		dataCollectionCacheModel.copiedFrom = getCopiedFrom();

		dataCollectionCacheModel.organizationId = getOrganizationId();

		dataCollectionCacheModel.hasMetaData = isHasMetaData();

		dataCollectionCacheModel.hasLayout = isHasLayout();

		return dataCollectionCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<DataCollection, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<DataCollection, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DataCollection, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((DataCollection)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<DataCollection, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<DataCollection, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<DataCollection, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((DataCollection)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, DataCollection>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();
	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _dataCollectionId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private long _statusByUserId;
	private String _statusByUserName;
	private Date _statusDate;
	private String _name;
	private String _originalName;
	private String _version;
	private String _originalVersion;
	private long _copiedFrom;
	private long _originalCopiedFrom;
	private boolean _setOriginalCopiedFrom;
	private long _organizationId;
	private long _originalOrganizationId;
	private boolean _setOriginalOrganizationId;
	private boolean _hasMetaData;
	private boolean _hasLayout;
	private long _columnBitmask;
	private DataCollection _escapedModel;

}